# Generated by Django 2.0.2 on 2018-02-27 02:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Actividad')),
                ('fecha', models.DateField(verbose_name='Fecha de la actividad')),
                ('hora', models.TimeField(verbose_name='Hora de la actividad')),
                ('notas', models.CharField(max_length=4000, verbose_name='Notas de la actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calle', models.CharField(blank=True, max_length=50, null=True)),
                ('Numero_Interior', models.CharField(blank=True, max_length=6, null=True)),
                ('Numero_Exterior', models.CharField(blank=True, max_length=6, null=True)),
                ('Colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('Ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('Estado', models.CharField(blank=True, max_length=50, null=True)),
                ('Pais', models.CharField(blank=True, max_length=50, null=True)),
                ('Codigo_Postal', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido_Paterno', models.CharField(max_length=50)),
                ('Apellido_Materno', models.CharField(max_length=50)),
                ('Telefono_Casa', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('Telefono_Celular', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('Metodo_Captacion', models.CharField(blank=True, max_length=50, null=True)),
                ('Interes', models.CharField(blank=True, max_length=50, null=True)),
                ('Estado_Civil', models.CharField(blank=True, max_length=15, null=True)),
                ('Ocupacion', models.CharField(blank=True, max_length=15, null=True)),
                ('Hijos', models.BooleanField(default=False)),
                ('Direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospectos.Lugar')),
            ],
        ),
    ]
